---
- name: Install multiple packages 
  hosts: all
  become: yes

  vars:
    packages:
      package_last:
        - nginx
        - curl 
        - git 
        - vim
  tasks:
    - name: Install latest version of package
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.package_last }}"